### ISSUE TITLE
Question: Can I use this extension for backend login?

### ISSUE THREAD

**Issue by parijke** [bolt/ClientLogin#19]
Id like to know if this extension can be connected to backend users for federated authentication?

Otherwise this would be a feature request

**Comment by GawainLynch** [comment]
I can not be currently, and is out of scope for this extension itself. 

With the upcoming Bolt 3, the associated release should provide a more useful API for another extension to potentially build on, but we won't be doing federated login with ClientLogin. It's a hard one to get right, and a lot of maintenance.

That said, if a skilled and dedicated person were to put their hand up and help with writing code, documentation and unit tests, it wouldn't take much convincing with me… I do however know there would be resistance from some core team members… but we might be able to bribe them with :beers: :grinning:
