### ISSUE TITLE
`Provider not given` error on authentication page

### ISSUE THREAD

**Issue by andyjessop** [bolt/ClientLogin#2]
I've set the authentication config like this:

    providers:
        Password:
            enabled: true

But when I visit the page `/authentication/login`, I get the above error. Is there any other configuration that needs to be done? I'm running Bolt 2.0

**Comment by GawainLynch** [comment]
Closing this as I am discontinuing the extension. It has been merged with [`bolt/members`](https://github.com/bolt/Members) and is for Bolt v3.0+
