### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by frantic777** [bolt/ClientLogin#3]
Sorry for asking here, but I haven't found any other way.
I'm quite new to Bolt and basically very far from php development, so it is quite tricky for me to understand how to use the extension. I have configured auth provider as per readme, but I'm unable to determine where the login page is located. Could you help me to find out how to get to social auth page?

**Comment by GawainLynch** [comment]
> Sorry for asking here, but I haven't found any other way.

No that is fine, this is the best place to ask! :+1: 

OK, so this comes down to what you do in your Twig template, this is a *very* basic example:
```twig
{% if hasauth() %}
    <h1>Welcome to the private area</h1>

   <p>insert page content here</p>
{% else %}
    {{ displaylogin(true) }}
{% endif %}
```
The `hasauth()` function will return true if the person is logged in, and in that part of the template you can show the "restricted" content.

The `displaylogin()` function will display the login buttons themselves.

**Comment by GawainLynch** [comment]
Also depending on what you're doing, this extension is very deliberately simple and we use it as a base for other extensions, e.g. `bolt/members` that will install this as a dependency and provides a bit of extra functionality — as I mentioned it just adds to this one.

**Comment by frantic777** [comment]
Thanks for answering!
I actually try to setup both extensions (login + members). Looks like I need to create login page by myself, but I wonder if there is something ready to use, e.g. theme which is already integrated with both of plugins and have related pages?

**Comment by GawainLynch** [comment]
Short answer is "no", a combination of time and the fact that I suck at frontend :grinning: 

What might help is to have a look at the Twig `{% block %}`'s that I use as a default install (that should work with a copy of `base-2014` theme) in [BoltBB](https://github.com/GawainLynch/bolt-extension-boltbb/blob/master/assets/forums/boltbb_forum.twig)

**Comment by frantic777** [comment]
Got it :-)
Thank you! Will try to do some coding soon

**Comment by frantic777** [comment]
I have setup the clientlogin on bolt 2.1.1 and it looks like either I did something wrong or there is an error. The issue is that one I'm logged on (via google) I'm still unable to get to entity which is limited by 'social' role. I have setup to be redirected to page with displayauth script once try to access restricted page, and once I have logged in, I still see this page (with "logout") button when trying to open such entry.

**Comment by frantic777** [comment]
Also "password" authenticator doesn't do anything

**Comment by GawainLynch** [comment]
> Also "password" authenticator doesn't do anything

Ah yes, that is due to it not having been implemented yet. It is something that we hope to do soon, but there are challenges.

> I'm still unable to get to entity which is limited by 'social' role.

The functionality that uses is in the process of being removed from Bolt altogether, as it was poorly implemented. The example in this [comment above](https://github.com/GawainLynch/bolt-extension-clientlogin/issues/3#issuecomment-78434930) is the way to go about it… i.e. the last part happens in the template.

**Comment by frantic777** [comment]
Oh, stupid me :-) didn't get that I shall not use frontend permissions at all. Now I have added a template for hidden entities and that works fine! Thank you! One more question, if you don't mind: is it possible to use instagram auth?

**Comment by GawainLynch** [comment]
Nah, you are good. If this stuff was easy everyone would be doing it :smile_cat: 

Instagram I never tried. Since this extension started life as Authenticate in Bolt 1.5, it has only used Hybridauth's default providers as that code base is… "interesting". That's not to say I can't add it though, I might see how I go this weekend.

**Comment by frantic777** [comment]
Appreciate that!

**Comment by frantic777** [comment]
Now I have tried 'members', but the issue is that most of functionality is not working (roles assignment, enable/disable user) is there any way to grant/restrict access to particular users?

**Comment by GawainLynch** [comment]
There is a big update to members coming soon that will finally finish the enable/disable.

However what does work now is the roles… But that is defined by extensions that want roles. Members only makes the assumption about membership and can check if a role is assigned or not… 

Been a huge time factor finishing this stuff up, many apologies.

**Comment by GawainLynch** [comment]
This is an example of how an [extension can define roles](https://github.com/GawainLynch/bolt-extension-boltbb/blob/master/Extension.php#L209)

**Comment by frantic777** [comment]
You're making great contribution by these extentions! Thank you for the example! I will have a look soon.

**Comment by GawainLynch** [comment]
Thank you, I do feel really bad for you though… I got these to the stage where it Works for Me&trade; and my needs and, yeah, time :grin:

**Comment by frantic777** [comment]
No worries :-)
BTW, I have added Instagram.php from hybridauth repo, and with minimal configuration it started to work. I will add it together with config and readme update to clientlogin plugin

**Comment by frantic777** [comment]
If you don't mind (accidentally tapped on close and comment)

**Comment by GawainLynch** [comment]
Closing this as I am discontinuing the extension. It has been merged with [`bolt/members`](https://github.com/bolt/Members) and is for Bolt v3.0+
