### ISSUE TITLE
session error when trying to connect via fb

### ISSUE THREAD

**Issue by nealmarques** [bolt/ClientLogin#4]
Catchable fatal error: Argument 2 passed to Bolt\Extension\Bolt\ClientLogin\ClientRecords::doCreateUserProfile() must be of the type array, object given, called in /Users/nmarques/Projects/playground/bolt_builds/ACC/extensions/vendor/bolt/clientlogin/src/Session.php on line 86 and defined in /Users/nmarques/Projects/playground/bolt_builds/ACC/extensions/vendor/bolt/clientlogin/src/ClientRecords.php on line 224

![screen shot 2015-04-01 at 10 10 56 pm](https://cloud.githubusercontent.com/assets/5342693/6952708/0cd0c28a-d8bc-11e4-9023-6867f1921bc5.png)

**Comment by GawainLynch** [comment]
This, and a tonne of other stuff, should now be fixed in master!

**Comment by GawainLynch** [comment]
Closing this as I am discontinuing the extension. It has been merged with [`bolt/members`](https://github.com/bolt/Members) and is for Bolt v3.0+
