### ISSUE TITLE
What's the current state of password auth?

### ISSUE THREAD

**Issue by andyjessop** [bolt/ClientLogin#6]
I can see that there's been some recent work on password auth - is this ready for primetime?

**Comment by GawainLynch** [comment]
Hi, no the master branch has a bit of breakage at the moment as a result of it. I am planning on working on it this weekend to get OAuth working again, and password authentication finished. It should only be a simple fix, probably a one-liner, but the debugging work is the hard part :grinning:

**Comment by babaggeii** [comment]
Great - will be keeping a close and excited eye on it!

**Comment by GawainLynch** [comment]
OK, there is now additional bits in there… beta testing and feedback most welcome!

**Comment by babaggeii** [comment]
I'll install tomorrow and give my feedback.

**Comment by andyjessop** [comment]
Bit late, but just about to test this. Is it v 2.1.0 that I need or is there a later dev version?

**Comment by GawainLynch** [comment]
Yes, you need the dev-master form both ClientLogin and Members at present as they require Bolt v2.2.0 due to upcoming changes with the Guzzle library.  That said, I have all of the above rolled out on the production site that I have that these were originally written for and are behaving.

**Comment by andyjessop** [comment]
Trying to install dev-master now, but I get this:

    Problem 1
        - Installation request for bolt/clientlogin dev-master -> satisfiable by bolt/clientlogin[dev-master].
        - bolt/clientlogin dev-master requires bolt/bolt >=2.2.0,<3.0.0 -> no matching package found.

**Comment by GawainLynch** [comment]
Yes, it requires Bolt >= v2.2.0 (which is currently Bolt master branch)

**Comment by andyjessop** [comment]
Ah, sorry - didn't see that. Thanks for the help.

**Comment by GawainLynch** [comment]
I got stuck between a rock and a hard place on version dependencies. We should have 2.2 beta out very soon though. :shipit:

**Comment by andyjessop** [comment]
Looking forward to it :)

**Comment by treeindark** [comment]
Authenticate by form can't be use ?

 Bolt \ Extension \ Bolt \ ClientLogin \ Exception \ ProviderException
but

providers:
    Password:
        enabled: true

**Comment by jmcmullen** [comment]
Has any progress been made with this? I can't get the form to appear.

**Comment by ticketbird** [comment]
I'm also interested in the status of the password authentication. I tried to install the master branch, but it now complains that it requires bolt >=2.3.0. I'm on 2.2.14. I tried installing with `"bolt/clientlogin": "dev-master@dev"` in extensions/composer.json.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for bolt/clientlogin dev-master@dev -> satisfiable by bolt/clientlogin[dev-master].
    - bolt/clientlogin dev-master requires bolt/bolt >=2.3.0,<3.0.0 -> no matching package found.
```

**Comment by GawainLynch** [comment]
OK… So… :grin: 

What was going to be Bolt 2.3 has been shifted to become Bolt 3.0 and is scheduled for release in Q1 2016. The master branch requires PHP 5.4+ due to the OAuth2 libraries, and as Bolt 2.2 was the last one to support PHP 5.3, master is requiring that version.

I have just been under a huge workload with Bolt's upcoming release, but I have some time put aside to work on this (finish it) early in 2016.

**Comment by skript-cc** [comment]
Ok, thanks for the info! (I inadvently posted the previous comment under the wrong --ticketbird-- account, now switched to this one.)

I'm planning to release a bolt based site somewhere in january, so it looks like Bolt 3.0 comes too late. I will have a look if it is feasible to fork the 2.1 branch and implement the password auth myself.

On a side note: is there a roadmap available somewhere to track these kind of things? I quickly checked the bolt site, but couldn't find anything.

**Comment by GawainLynch** [comment]
I would guess that I'll be trying to get the next release of this extensions done in January some time, and I might enable Bolt 2.2 support for it. On porting it to the new extension model about to land for Bolt 3 should be pretty straightforward… and I have a need for it on a site that I don't have the time to update to Bolt 3 in the short term myself.

There is a Bolt [Roadmap](https://github.com/bolt/bolt/wiki/Bolt-2.x-Roadmap), it will get more updates once we put Bolt 3 into beta in a few weeks. Been a busy and long year for all of us :grin:

**Comment by skript-cc** [comment]
That sounds very interesting. Perhaps I can help with the 2.2 support?

I'm quite new to Bolt, but it looks like you are doing great work! Very much appreciated, keep it up :)

**Comment by GawainLynch** [comment]
> Perhaps I can help with the 2.2 support?

Potentially. I have a few things locally that I need to finish (soon!) and then I'll let you know and we'll see how we can collaborate.

Thank you for the compliments. We have a great time making the product and we hope to continue kicking bigger goals in 2016 :grin:

**Comment by skript-cc** [comment]
I already got a bit ahead of things this week and managed to get the master branch working on a bolt 2.2 installation. Facebook login is working at this point, but so far as I can see the local e-mail/password login is not completely implemented yet. The login form does check the credentials, but it doesn't log the user in (i.e. it doesn't store a session or cookie). I also couldn't find an easy way to get this working, because the methods that are already in place for this expect an OAuth access token (and I had a hard time wrapping my head around the authorization flow).

@GawainLynch Before further digging into this I will wait for you to complete your changes. Just wanted to let you know about the progress I've made so far.

**Comment by GawainLynch** [comment]
Note there is a whole bunch of breakage that landed in master two days ago that will render 2.2 not workable at all due to the way that 2.2 abuses sessions.

I can't remember where I got to at that point you forked, but the plan is to implement local OAuth password grants, via the local provider.

**Comment by skript-cc** [comment]
Looks like I started working based on the commits you pushed last tuesday. I didn't fork the repo yet, just did a checkout of the master branch, and installed it as local extension.

I also ran into some session trouble. Stored class instances didn't get properly deserialized. Managed to work around this by manually requiring the classes in index.php. It's pugugly, but it gets the job done. Is that the same issue you're referring to? 

About the password grants, that is usually something that is handled by the authorisation server, right? And everything that is implemented now under OAuth2/ResourceServer (i.e. the providers) is actually an implementation of the OAuth2/Client library? So does this mean that you plan to implement the OAuth2 authorization server with password grants, (just) to get the local login working?

I understand this is a nice solution if you look at it from the perspective of uniformity - everything gets implemented as OAuth2. But it also feels like you're taking a pretty big detour to get a simple job done. Implementing an authorization server for bolt could be an extension on its own.

**Comment by GawainLynch** [comment]
Yes, that is the session problem I referred to. Basically, prior to the controller & session work that @CarsonF and I did in Bolt's current master last year, sessions would get initiated during bootstrap meaning that the session code has no way to know about classes included after that point.

Yes, the local login is being done using an [authorisation server](https://github.com/bolt/ClientLogin/tree/master/lib/League/OAuth2/Server), which is the sister library to the [resource server](https://github.com/bolt/ClientLogin/tree/master/lib/League/OAuth2/Client). The namespace you [refer to](https://github.com/bolt/ClientLogin/tree/master/src/OAuth2/ResourceServer) is just where we extend the providers to get some consistency of implementation.

While the password implementation looks simple on the surface, trying to jerry-rig that into an OAuth work flow was hard, and prone to breaking repeatedly. I spent a long time working on that in a now-deleted-branch and just gave up as it was almost un-testable and I didn't fancy supporting it :grin:

**Comment by GawainLynch** [comment]
@skript-cc also please note an important security warning, that [this line](https://github.com/bolt/ClientLogin/blob/master/src/Authorisation/CookieManager.php#L43) should not go into production as-is… it current state is there to make my life easy while debugging… 'cause lazy :grin:

**Comment by skript-cc** [comment]
Oke, I get the idea. But I do think calling the [OAuth2 Client library](https://github.com/bolt/ClientLogin/tree/master/lib/League/OAuth2/Client) a 'resource server' is confusing. If you look at the original OAuth2 libraries you can see that the [Client library](http://oauth2-client.thephpleague.com/) is different from the [Server library](http://oauth2.thephpleague.com/). The Server library furthermore makes a difference between an 'authorization server' and a 'resource server'. The [terminology page](http://oauth2.thephpleague.com/terminology/) defines it as follows:

>Authorization server - A server which issues access tokens after successfully authenticating a client and resource owner, and authorizing the request.
> [...]
> Resource server - A server which sits in front of protected resources (for example “tweets”, users’ photos, or personal data) and is capable of accepting and responsing [sic] to protected resource requests using access tokens.

The providers of the [Client library](http://oauth2-client.thephpleague.com/) don't sit in front of protected resources, but are a way to connect to OAuth2 service providers (i.e. servers).

I'm sorry to quibble about terminology, but everything started to make more sense to me when I started to understand the difference between clients and servers.

**Comment by skript-cc** [comment]
Btw, thanks for the security warning :)

**Comment by GawainLynch** [comment]
From the [OAuth2 spec](https://tools.ietf.org/html/rfc6749)
```
1.1.  Roles

   OAuth defines four roles:

   resource owner
      An entity capable of granting access to a protected resource.
      When the resource owner is a person, it is referred to as an
      end-user.

   resource server
      The server hosting the protected resources, capable of accepting
      and responding to protected resource requests using access tokens.

   client
      An application making protected resource requests on behalf of the
      resource owner and with its authorization.  The term "client" does
      not imply any particular implementation characteristics (e.g.,
      whether the application executes on a server, a desktop, or other
      devices).

   authorization server
      The server issuing access tokens to the client after successfully
      authenticating the resource owner and obtaining authorization.
```

**Comment by skript-cc** [comment]
Yes, indeed. So for example, when someone logs in with facebook on a bolt site, the user is the **resource owner**, the bolt site is the **client** and facebook is the **authorization server** (it issues an access token) *and* **resource server** (it responds to protected resource requests using access tokens, e.g. when making api calls). The fact that while logging in, facebook is primarily used as an authorization server and not as a resource server, doesn't mean that the bolt site becomes a resource server. In the OAuth scheme, it just remains a client.

**Comment by GawainLynch** [comment]
OK… and I have a head full of influenza right now, so excuse the level of potential derp here.

But the design goal of ClientLogin *is* to provide a base RS… "Yes, you have an AccessToken, yes your account is enabled, and yes, you are allowed to access *restricted* parts of *this Bolt site*"

**Comment by skript-cc** [comment]
Sorry to hear you're sick, all the best! Regardless of that, I think this is a fruitful discussion. I understand what you are saying, but I don't agree.

I will try to explain. I don't think the goal of ClientLogin is to provide an *OpenAuth* Resource Server, because you don't want to allow *third parties* to access restricted resources. Instead the goal is to offer users access to a restricted part of a bolt site. OpenAuth only comes into play because you want to provide the possibility for users to use a third party (i.e. an already existing account) to authenticate. As such, you are only acting as an OpenAuth Client and not as an OpenAuth Server. You don't *issue* access tokens to third parties, but only store and use access tokens issued by other OpenAuth providers.

**Comment by GawainLynch** [comment]
All good on the sick part… More just warning you that I am not "on my game" right now.

Yeah, very fruitful conversation.

> I don't think the goal of ClientLogin is to provide an OpenAuth Resource Server, 

To a not so insignificant extent, that is what I foresee in the future of this, and one of my design goals. That said, you'd be right in assuming it is not needed *now*.

Building in an Authorisation Server however, is a here-and-now goal… and one we require for something else we're using this for.

OK, so moving on… What do you see as a workable approach?

**Comment by skript-cc** [comment]
I'm not sure about a workable approach in this situation. Like I said earlier, I don't see an easy way to get the login form working (i.e. without building an authorisation server). Almost everything for a local authentication is present when you render and check the login form in the [local authorization handler](https://github.com/bolt/ClientLogin/blob/master/src/Authorisation/Handler/Local.php#L71-L94). You check the username and password, you handle incorrect credentials, you only don't set the login state in a session/coockie. In principle this would be a very simple operation, but the way you handle this for openAuth logins is thoroughly intertwined with access tokens, which you don't have or need for local logins.

So I guess one approach is to build the authorisation server like your planning, with which you can also issue access tokens for local users. The other, perhaps quicker, approach would be to provide a way to set a session/cookie without an access token.

**Comment by skript-cc** [comment]
I also think that ideally, the oAuth authorisation/resource server should be implemented as another plugin. The way I see it -- and this is also very much coloured by my needs -- is that the clientlogin extension provides a way to let users of a bolt site access restricted areas of that site. This can be achieved either through authentication with a third party oauth service, or by creating an account on the site and authenticating with the saved credentials.

The need to open up these accounts and related resources to other clients could then be covered in an oauth-server extension, or whatever you want to call it.

**Comment by skript-cc** [comment]
Just out of curiosity: What's the reason you have chosen to store users in a separate account table, and not to built upon bolts existing users & permissions functionality?

**Comment by GawainLynch** [comment]
Easiest one first :grin: 

> What's the reason you have chosen to store users in a separate account table, and not to built upon bolts existing users & permissions functionality?

Many. First and foremost it is bad security practice to mix client and secure. Second the level of trust of OAuth is pretty low in the community, and as such has been ruled out in more discussions than I care to remember over the last 2 years.

**Comment by GawainLynch** [comment]
> So I guess one approach is to build the authorisation server like your planning, with which you can also issue access tokens for local users. The other, perhaps quicker, approach would be to provide a way to set a session/cookie without an access token.

Yeah, that one isn't optional for us. It is currently what I am working on for a couple of project's requirements.

**Comment by GawainLynch** [comment]
> I also think that ideally, the oAuth authorisation/resource server should be implemented as another plugin. 

I honestly agree with you… 

But I am working hard to get Bolt 3 out the door, coordinate the core Bolt development team, hold down two jobs, and have been helped with a sum total of 7 commits out of the 900 or so that have gone into the extension… so I had to make design sacrifices to save time and energy, very much at the cost of my own OCD :grin:

**Comment by GawainLynch** [comment]
Oh, something else that I keep forgetting to include here.

The whole thing needs to tie into consistent events, as the event data is passed to other extensions, namely Members… and that's what pulled me up when I started this new version, the login auth, as you noticed, works fine, but getting consistent objects to pass around become more and more nasty.

**Comment by skript-cc** [comment]
>> What's the reason you have chosen to store users in a separate account table, and not to built upon  bolts existing users & permissions functionality?

> Many. First and foremost it is bad security practice to mix client and secure. Second the level of trust of OAuth is pretty low in the community, and as such has been ruled out in more discussions than I care to remember over the last 2 years. 

Ok, I see.

> Yeah, that one isn't optional for us. It is currently what I am working on for a couple of project's requirements.

So, which one isn't optional? The authorisation server or the session/cookie without an access token? I assume the first one.

> I had to make design sacrifices to save time and energy

We all have to do that from time to time :) But it is good to have some overview of the current state of affairs and the state you ideally would want to achieve and aspire. It would be great if stuff like this in the future could be communicated on the README page, perhaps in the form of a 'current issues' section.

**Comment by GawainLynch** [comment]
> So, which one isn't optional? The authorisation server or the session/cookie without an access token? I assume the first one.

Well, I was indicating the auth server in that comment, but given how heavily auth tokens are stitched into OAuth, to a certain extent "both".

> It would be great if stuff like this in the future could be communicated on the README page, perhaps in the form of a 'current issues' section.

Noted… Just need to finish the code first. :smile:

**Comment by skript-cc** [comment]
Two more questions: 

1. Do you already have a date when you expect this to be done?

I don't mean to push you, but I need a bolt username/password login myself really soon. I also don't mind to collaborate and contribute some code, but considering our discussion I get the impression we pursue different goals. 

So I have been looking around for alternative solutions and came across the [Silex SecurityServiceProvider](http://silex.sensiolabs.org/doc/providers/security.html) and [a third party oAuth service provider](https://github.com/gigablah/silex-oauth) which is compatible with it. It looks like these two things cater for everything I need, and to some extent for what you are trying to achieve. So here comes my second question:

2. Is there any particular reason why you don't use the Silex Security Provider?

I also got the impression it is not used by Bolt itself, which I found slightly odd considering Bolt is built on Silex. So I  figured perhaps there is another reason...

**Comment by GawainLynch** [comment]
> Do you already have a date when you expect this to be done?

Not taken as pushing btw :grin: 

Yeah, the deadline is some time in March, but realistically very soon. I have a lot of it working in my local branch, but have been getting my arse kicked by this damn flu so all representations of "work" have been slow.

What I will say though, that might influence your decision. We have very firmly gone with Bolt 3 as the platform for this, and the code base has dropped it's use of a "local" Guzzle 6 library, and the extension loader has mostly been updated to reflect that.

That said, backporting wouldn't be too hard if someone wanted to, but the session thing is going to be the biggest issue in using 2.2, thus not making it suitable for a broader release.

> Is there any particular reason why you don't use the Silex Security Provider?

Yeah. This extension grew out of a Bolt v1 extension and so an and so forth. We're hoping to move Bolt itself to either the Symfony or Silex Security Provider in v4, but it is just too much work for now. I know it could be done specifically for these routes, but like you I just wanted something out the door… mainly so I could get on with Bolt core stuff :grin: 

Correct decision on my part… probably not.
Stuck with it for now… pretty much.

**Comment by skript-cc** [comment]
Thank you for taking the time to answer all my questions. Considering the route you are taking, it looks like the best thing for me to do is to build my own login extension. Hopefully I can make a bolt extension out of it, and release it under an open source license.

**Comment by GawainLynch** [comment]
Closing this as I am discontinuing the extension. It has been merged with [`bolt/members`](https://github.com/bolt/Members) and is for Bolt v3.0+

P.S. Yes, password authentication is in and working :grin:
